[project]
name = "organizador-download"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kaire Viana", email = "kaireviana20@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "rich>=15.0.0",
]

[project.scripts]
organizador-download = "organizador_download:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
